server:
  port: 5050

jwt:
  signer-key: "B+jgFk5rkhAinZn4u41/0oWk9SKpPRCob+bkV7XKZKO0WSDlsrasiE9myU4MeicG"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_final_java05
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


